import type { Metadata } from "next";
import { LegalSection, MarketingLegalShell } from "@/components/landing/MarketingLegalShell";

export const metadata: Metadata = {
  title: "Terms of Use · NyaySahayak",
  description: "Terms for using NyaySahayak — guidance companion, not a law firm or emergency service.",
};

export default function TermsPage() {
  return (
    <MarketingLegalShell title="Terms of Use" updated="24 July 2026">
      <LegalSection title="Agreement">
        <p>
          By creating an account or using NyaySahayak, you agree to these Terms and our Privacy Policy. If you
          do not agree, do not use the service.
        </p>
      </LegalSection>

      <LegalSection title="What NyaySahayak is">
        <p>
          NyaySahayak is an AI-powered legal companion that helps you understand options, organise your
          situation, prepare drafts, and connect with human help. It provides guidance and navigation — not
          guaranteed legal outcomes and not licensed legal representation unless separately arranged with a
          lawyer.
        </p>
      </LegalSection>

      <div id="disclaimer">
        <LegalSection title="Disclaimer">
          <p>
            Content generated by the product may be incomplete or incorrect. Always verify critical steps with
            qualified professionals and official sources. NyaySahayak is not a substitute for emergency
            services. If you or someone else is in immediate danger, dial 112 (or your local emergency number)
            first.
          </p>
        </LegalSection>
      </div>

      <LegalSection title="Accounts and acceptable use">
        <p>
          You are responsible for your account credentials and for the accuracy of information you provide. Do
          not misuse the service, attempt unauthorized access, upload unlawful content, or harass others. We
          may suspend accounts that threaten safety or system integrity.
        </p>
      </LegalSection>

      <LegalSection title="Human helpers and third parties">
        <p>
          Connections to moderators, Nyay Guides, lawyers, helplines, or government portals are facilitation
          tools. Those parties may have their own terms. Lawyer verification on the platform does not replace
          your independent diligence.
        </p>
      </LegalSection>

      <LegalSection title="Clash Mode and educational tools">
        <p>
          Practice and debate features (including Clash Mode) are educational. They are not court rulings,
          formal legal opinions, or advice you should file without review.
        </p>
      </LegalSection>

      <LegalSection title="Fees">
        <p>
          Getting started and initial guidance is free. Some formal services or lawyer connections may involve
          separate fees or terms, which we will explain before you commit.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>
          To the fullest extent permitted by law, NyaySahayak and its operators are not liable for decisions
          you make based on product guidance, third-party actions, or service interruptions. Nothing in these
          Terms limits rights that cannot be limited under applicable law.
        </p>
      </LegalSection>

      <LegalSection title="Changes">
        <p>
          We may update these Terms as the product changes. Continued use after an update means you accept the
          revised Terms. The “Last updated” date reflects the latest revision.
        </p>
      </LegalSection>
    </MarketingLegalShell>
  );
}
