#!/usr/bin/env python3
"""End-to-end smoke test for the Improvise Policies studio.

Reindexes the context catalog, runs a semantic search, streams a draft, then
checks that embedding usage landed in ai_usage_logs.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv

load_dotenv(ROOT / ".env")

from backend.database.postgres_pool import execute  # noqa: E402
from backend.services import policy_context, policy_impact, policy_studio  # noqa: E402
from backend.services.admin_models import read_config_key  # noqa: E402

# Generated by: cd web_app && npx @openuidev/cli generate
#   ./components/admin/policy/policy-genui-library.tsx --out ./.openui/policy-system-prompt.txt
# The browser sends questionPrompt()/impactPrompt() instead; this is the same
# component contract, and without it the model has no reason to emit OpenUI Lang.
GENUI_PROMPT_FILE = ROOT / "web_app" / ".openui" / "policy-system-prompt.txt"

FALLBACK_PROMPT = (
    "Respond only with OpenUI Lang. Every program defines `root = Stack([...])` and "
    "arguments are positional."
)


def step(label: str) -> None:
    print(f"\n=== {label} ===")


def load_genui_prompt() -> str:
    if GENUI_PROMPT_FILE.exists():
        print(f"  using generated library prompt ({GENUI_PROMPT_FILE.name})")
        return GENUI_PROMPT_FILE.read_text(encoding="utf-8")
    print("  [warn] generated prompt missing - run `openui generate`; using fallback")
    return FALLBACK_PROMPT


def check_openui(kind: str, content: str) -> None:
    """The renderer needs assignment-based OpenUI Lang, never JSON or prose."""
    head = content.lstrip()[:60].replace("\n", " ")
    if content.lstrip().startswith(("{", "[", "```")):
        print(f"  [FAIL] {kind} is not OpenUI Lang: {head}")
    elif "root =" not in content:
        print(f"  [FAIL] {kind} has no root assignment: {head}")
    else:
        print(f"  {kind} parses as OpenUI Lang")


def check_implement_rollback() -> None:
    """Apply a reversible config change end to end, then undo it.

    The drafted policy above rarely produces a writable config change, so this
    uses a hand-built change set to cover write_config_key + audit + rollback.
    """
    step("Implement and rollback")
    scope = "chat_agent.supervisor"
    before = read_config_key("rag_retrieval", {}) or {}
    original_top_k = ((before.get("chat_agent") or {}).get("top_k")) or 10
    target_top_k = 6 if original_top_k != 6 else 7
    print(f"  rag_retrieval.chat_agent.top_k starts at {original_top_k}")

    plan = {
        "summary": "Verification-only policy. Narrows chat retrieval by one step.",
        "policy_text": "## Verification\nIgnore this rule; it exists only for a smoke test.",
        "config_changes": [
            {
                "key": "rag_retrieval",
                "path": "chat_agent.top_k",
                "from": original_top_k,
                "to": target_top_k,
                "reason": "smoke test",
            }
        ],
        "agent_scope": [scope],
        "manual_followups": [],
        "open_questions": [],
        "risk": "low",
        "ready": True,
    }
    draft = policy_studio.save_draft(
        policy_id=None,
        title="[verify] rag retrieval top_k",
        description="Automated verification of implement/rollback.",
        plan=plan,
        context_refs=[],
        answers={},
        created_by=None,
    )
    policy_id = draft["id"]

    try:
        result = policy_studio.implement_policy(policy_id, actor_id=None)
        applied_now = (read_config_key("rag_retrieval", {}) or {}).get("chat_agent", {}).get("top_k")
        print(f"  implemented: applied={len(result['applied'])} skipped={len(result['skipped'])}")
        print(f"  system_config now top_k={applied_now} (status {result['policy']['status']})")
        assert applied_now == target_top_k, "system_config was not updated"
        assert result["policy"]["status"] == "active"

        injected = policy_studio.get_active_policy_text(scope)
        print(f"  policy text reaches {scope}: {'yes' if 'Verification' in injected else 'NO'}")
        assert "Verification" in injected, "active policy text is not injected into the agent scope"

        rolled = policy_studio.rollback_policy(policy_id, actor_id=None)
        restored_top_k = (read_config_key("rag_retrieval", {}) or {}).get("chat_agent", {}).get("top_k")
        print(f"  rolled back: restored={rolled['restored']} top_k={restored_top_k}")
        assert restored_top_k == original_top_k, "rollback did not restore the previous value"
        assert rolled["policy"]["status"] == "rolled_back"

        after_rollback = policy_studio.get_active_policy_text(scope)
        assert "Verification" not in after_rollback, "rolled back policy text is still injected"

        audit = execute(
            """
            SELECT action FROM public.admin_audit_logs
            WHERE target_table = 'policy_documents' AND detail->>'policy_id' = %s
            ORDER BY created_at
            """,
            (policy_id,),
        )
        actions = [r["action"] for r in audit]
        print(f"  admin_audit_logs: {actions}")
        assert "policy_implement" in actions and "policy_rollback" in actions
    finally:
        execute("DELETE FROM public.policy_documents WHERE id = %s RETURNING id", (policy_id,))
        execute(
            "DELETE FROM public.admin_audit_logs WHERE detail->>'policy_id' = %s RETURNING id",
            (policy_id,),
        )


def main() -> None:
    step("Reindex policy context")
    counts = policy_context.reindex_policy_context()
    print(counts)
    print(policy_context.index_status())

    step("Semantic search")
    hits = policy_context.search_policy_context(
        "moderator review speed for domestic violence cases", top_k=5
    )
    for hit in hits:
        print(f"  {hit['similarity']:.3f}  {hit['kind']:>7}  {hit['title']}")
    assert hits, "semantic search returned nothing - is the embedding provider reachable?"

    step("Impact snapshot")
    snapshot = policy_impact.impact_snapshot(30)
    print(
        f"  cases={snapshot['cases']['total']} users={snapshot['users']['total']} "
        f"ai_requests={snapshot['ai']['requests']}"
    )

    step("Draft stream")
    genui_prompt = load_genui_prompt()
    events: list[dict] = []
    for line in policy_studio.stream_policy_session(
        description=(
            "Domestic violence cases from rural districts should skip the local forum "
            "suggestion and go straight to a female lawyer, and moderators must review "
            "them within 45 minutes."
        ),
        genui_prompt=genui_prompt,
        impact_prompt=genui_prompt,
        period_days=30,
    ):
        event = json.loads(line)
        events.append(event)
        kind = event.get("type")
        if kind == "stage":
            print(f"  stage: {event['label']}")
        elif kind == "plan":
            plan = event["plan"]
            print(f"  plan risk={plan['risk']} ready={plan['ready']}")
            print(f"  config_changes={len(plan['config_changes'])}")
            print(f"  open_questions={plan['open_questions']}")
        elif kind in ("questions_ui", "impact_ui"):
            print(f"  {kind}: {len(event['content'])} chars")
            check_openui(kind, event["content"])
        elif kind == "saved":
            print(f"  saved policy {event['policy']['id']} ({event['policy']['status']})")
        elif kind == "error":
            print(f"  ERROR: {event['message']}")

    saved = next((e["policy"] for e in events if e.get("type") == "saved"), None)

    check_implement_rollback()

    step("Embedding usage in ai_usage_logs")
    rows = execute(
        """
        SELECT task, model, provider, COUNT(*)::int AS calls,
               COALESCE(SUM(total_tokens), 0)::bigint AS tokens
        FROM public.ai_usage_logs
        WHERE task LIKE 'embedding.%'
        GROUP BY task, model, provider
        ORDER BY calls DESC
        """
    )
    for row in rows:
        print(f"  {row['task']:<22} {row['model']:<28} calls={row['calls']} tokens={row['tokens']}")
    assert rows, "no embedding.* rows were logged"

    step("Policy studio usage in ai_usage_logs")
    for row in execute(
        """
        SELECT task, model, COUNT(*)::int AS calls
        FROM public.ai_usage_logs
        WHERE task LIKE 'policy_studio.%'
        GROUP BY task, model ORDER BY calls DESC
        """
    ):
        print(f"  {row['task']:<26} {row['model']:<28} calls={row['calls']}")

    if saved:
        step("Cleanup draft")
        execute("DELETE FROM public.policy_documents WHERE id = %s RETURNING id", (saved["id"],))
        print(f"  removed {saved['id']}")

    print("\nAll checks passed.")


if __name__ == "__main__":
    main()
